### ISSUE TITLE
TypeError: Cannot assign to read only property 'name'

### ISSUE THREAD

**Issue by synthecypher** [h5bp/generator-server-configs#8]
Any ideas?
```
λ yo server-configs
C:\Users\Josh\AppData\Roaming\npm\node_modules\generator-server-configs\app\index.js:156
Generator.name = 'H5BP Server Configs';
               ^
TypeError: Cannot assign to read only property 'name' of function () {
                yeoman.generators.Base.apply(this, arguments);

                this.option('destination');
                this.argument('...<omitted>...  }
    at Object.<anonymous> (C:\Users\Josh\AppData\Roaming\npm\node_modules\generator-server-configs\app\index.js:156:16)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.defineProperty.get [as server-configs:app] (C:\Users\Josh\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\Josh\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\Josh\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:228:16)
```

**Comment by sindresorhus** [comment]
Fixed in 1.0.1.
